#!/usr/bin/env bash

set -eux

source "${OPS_ROOT}"/helpers/snap-logger.sh "hook-post-refresh"
source "${OPS_ROOT}"/helpers/config-location.sh
source "${OPS_ROOT}"/helpers/set-conf.sh

replace_stale_jars() {
    declare -a common=(modules plugins lib)
    for dir in "${common[@]}"; do
        setpriv \
            --clear-groups \
            --reuid snap_daemon \
            --regid snap_daemon -- \
            "${SNAP}/usr/bin/rsync" -a --delete \
            "${SNAP}/usr/share/opensearch/${dir}/" \
            "${OPENSEARCH_HOME}/${dir}/"
    done
}

# The previous revisions documented 'snap start opensearch.daemon' after
# setting up the node, which leaves the daemon disabled: snapd keeps it
# disabled, and so stopped, after the refresh. The daemon is enabled on
# install since this revision: enable it if the node was set up.
enable_daemon_if_set_up() {
    if [ "${CONFIG_MIGRATED}" == "yes" ] && config_is_set_up; then
        snapctl start --enable "${SNAP_INSTANCE_NAME}.daemon"
    fi
}

migrate_config_to_common
replace_in_file "${OPENSEARCH_PATH_CONF}/jvm.options" '^-XX:HeapDumpPath=data$' "-XX:HeapDumpPath=${OPENSEARCH_VARLOG}/java_heapdump.hprof"
replace_stale_jars
enable_daemon_if_set_up
