[tox]
env_list = lint, smoke
skip_missing_interpreters = true

[testenv:lint]
description = run linting for all OpenSearch / OpenSearch Dashboards artifacts
skip_install = true
allowlist_externals =
    tox
commands =
    tox -c opensearch/rocks/opensearch/tox.ini -e lint