#!/usr/bin/env bash

set -eux

source "${OPS_ROOT}"/helpers/snap-logger.sh "hook-post-refresh"

replace_stale_jars() {
    declare -a common=(modules plugins lib)
    for dir in "${common[@]}"; do
        setpriv \
            --clear-groups \
            --reuid snap_daemon \
            --regid snap_daemon -- \
            "${SNAP}/usr/bin/rsync" -a --delete \
            "${SNAP}/usr/share/opensearch/${dir}/" \
            "${OPENSEARCH_HOME}/${dir}/"
    done
}

replace_stale_jars

# Create a dummy folder to test refresh
mkdir -p ${SNAP_DATA}/dummy-folder
chown 584788:root ${SNAP_DATA}/dummy-folder
