#!/usr/bin/env bash

set -eux


source "${OPS_ROOT}"/helpers/io.sh
source "${OPS_ROOT}"/helpers/config.sh


# The configuration lives in $SNAP_COMMON and is kept across refreshes;
# this only seeds or migrates it when it is missing.
seed_config
