name: Rock Lint

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  discover-rocks:
    uses: ./.github/workflows/rocks-discover.yaml

  lint:
    name: Lint | ${{ matrix.rock.name }}
    runs-on: ubuntu-latest
    needs: discover-rocks
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        rock: ${{ fromJSON(needs.discover-rocks.outputs.rocks) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install tox
        run: python3 -m pip install tox

      - name: YAML Lint
        working-directory: ${{ matrix.rock.path }}
        run: tox run -e lint

    permissions:
      contents: read