name: Snap Lint

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  discover-snaps:
    uses: ./.github/workflows/snaps-discover.yaml

  lint:
    name: Lint | ${{ matrix.snap.name }}
    runs-on: ubuntu-latest
    needs: discover-snaps
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        snap: ${{ fromJSON(needs.discover-snaps.outputs.snaps) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install tox
        run: python3 -m pip install tox

      - name: YAML Lint
        working-directory: ${{ matrix.snap.path }}
        run: tox run -e lint

    permissions:
      contents: read